/* Generates MapData.html from world-atlas. Run by hand, output committed.
 *
 *     node tools/gen-map.mjs
 *
 * Committed rather than built because Apps Script does not run build.js — doGet
 * renders Index.html through HtmlService, so anything only build.js produces is
 * missing from /exec. And d3-geo/topojson stay devDependencies: shipping them to
 * the browser would be ~200KB and sw.js caches only '/', so a runtime dependency
 * breaks the app offline.
 */
import { geoNaturalEarth1, geoPath } from "d3-geo";
import { merge, mesh } from "topojson-client";
import { presimplify, simplify } from "topojson-simplify";
import { createRequire } from "module";
import { writeFileSync } from "fs";
const require = createRequire(import.meta.url);
const worldRaw = require("world-atlas/countries-110m.json");

const W = 1600, H = 885, LAND_BOTTOM = 742;

const world = simplify(presimplify(worldRaw), 0.06);
const geometries = world.objects.countries.geometries.filter(g => g.id !== "010"); // no Antarctica
const landGeo = merge(world, geometries);

const projection = geoNaturalEarth1().fitExtent([[20, 24], [W - 20, LAND_BOTTOM]], landGeo);
const path = geoPath(projection);
const round = s => s.replace(/\d+\.\d+/g, m => (+m).toFixed(1));

const land    = round(path(landGeo));
const borders = round(path(mesh(world, { type: "GeometryCollection", geometries }, (a, b) => a !== b)));

/* The browser needs to place a pin for any country the Levels sheet names, not
 * only the ones known today — so it gets the projection itself, not a lookup.
 * naturalEarth1 is a closed-form polynomial; these are d3's own coefficients. */
const k = projection.scale(), t = projection.translate();
function naturalEarth1(lonDeg, latDeg) {
  const l = lonDeg * Math.PI / 180, p = latDeg * Math.PI / 180;
  const p2 = p * p, p4 = p2 * p2;
  return [
    l * (0.8707 - 0.131979 * p2 + p4 * (-0.013791 + p4 * (0.003971 * p2 - 0.001529 * p4))),
    p * (1.007226 + p2 * (0.015085 + p4 * (-0.044475 + 0.028874 * p2 - 0.005916 * p4)))
  ];
}
const mine = (lon, lat) => {
  const [x, y] = naturalEarth1(lon, lat);
  return [t[0] + k * x, t[1] - k * y];
};

/* Verified against d3 before anything is written. A reimplementation that is
 * close but not equal puts every pin slightly off its country, which is exactly
 * the failure this replaces. */
let worst = 0;
for (let lon = -180; lon <= 180; lon += 7.5) {
  for (let lat = -60; lat <= 80; lat += 7) {
    const a = projection([lon, lat]), b = mine(lon, lat);
    worst = Math.max(worst, Math.abs(a[0] - b[0]), Math.abs(a[1] - b[1]));
  }
}
console.log('projection parity vs d3: worst axis error %s px over %d points',
            worst.toExponential(2), 25 * 21);
if (worst > 0.001) { console.error('REFUSING TO WRITE: the inline projection does not match d3.'); process.exit(1); }

const out = `<script>
/* GENERATED by tools/gen-map.mjs — do not edit by hand.
 *
 * Natural Earth projection of world-atlas countries-110m, simplified at 0.06,
 * Antarctica removed. Committed rather than built: Apps Script renders Index.html
 * through HtmlService and never runs build.js.
 *
 * H (${H}) is deliberately taller than the land box (${LAND_BOTTOM}) — that gap is
 * the open sea below Australia. Do not collapse the two.
 */
window.LM_MAP = {
  W: ${W}, H: ${H}, LAND_BOTTOM: ${LAND_BOTTOM},
  scale: ${k}, tx: ${t[0]}, ty: ${t[1]},
  land: '${land}',
  borders: '${borders}'
};
/* lon/lat to stage pixels. d3's own naturalEarth1 coefficients; tools/gen-map.mjs
 * refuses to emit this file unless it reproduces d3 to within 0.001px. */
window.LM_PROJECT = function (lon, lat) {
  var l = Number(lon) * Math.PI / 180, p = Number(lat) * Math.PI / 180;
  var p2 = p * p, p4 = p2 * p2;
  var x = l * (0.8707 - 0.131979 * p2 + p4 * (-0.013791 + p4 * (0.003971 * p2 - 0.001529 * p4)));
  var y = p * (1.007226 + p2 * (0.015085 + p4 * (-0.044475 + 0.028874 * p2 - 0.005916 * p4)));
  return { x: window.LM_MAP.tx + window.LM_MAP.scale * x,
           y: window.LM_MAP.ty - window.LM_MAP.scale * y };
};
</script>
`;
writeFileSync(new URL('../MapData.html', import.meta.url), out);
console.log('MapData.html written: %s KB  (land %s, borders %s)',
            (out.length / 1024).toFixed(1), land.length.toLocaleString(), borders.length.toLocaleString());
